# Generated by Django 5.1 on 2024-09-10 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=200)),
                ('background_size', models.CharField(max_length=200)),
                ('background_position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', models.CharField(max_length=200)),
                ('border_radius', models.PositiveIntegerField()),
                ('border_color', models.CharField(max_length=200)),
                ('border_style', models.CharField(choices=[('dotted', 'dotted'), ('dashed', 'dashed'), ('solid', 'solid'), ('double', 'double'), ('none', 'none')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('choice', 'Choice'), ('url', 'URL'), ('file', 'File'), ('image', 'Image')], max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LayoutSizing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('padding', models.PositiveIntegerField()),
                ('margin', models.PositiveIntegerField()),
                ('display', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(max_length=200)),
                ('font_family', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('text_align', models.CharField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT'), ('CENTER', 'CENTER'), ('JUSTIFY', 'JUSTIFY')], max_length=200)),
                ('text_transform', models.CharField(choices=[('UPPERCASE', 'UPPERCASE'), ('LOWERCASE', 'LOWERCASE'), ('CAPITALIZE', 'CAPITALIZE')], max_length=200)),
                ('letter_spacing', models.PositiveIntegerField()),
                ('line_height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_shadow', models.CharField(max_length=200)),
                ('opacity', models.PositiveIntegerField()),
                ('visibility', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('readonly', models.BooleanField()),
                ('disabled', models.BooleanField()),
                ('size', models.CharField(choices=[('QUARTER', 25), ('HALF', 50), ('FULL', 100)], max_length=200)),
                ('maxlength', models.PositiveIntegerField()),
                ('min', models.PositiveIntegerField()),
                ('max', models.PositiveIntegerField()),
                ('multiple', models.BooleanField()),
                ('pattern', models.CharField(max_length=200)),
                ('placeholder', models.CharField(max_length=200)),
                ('autofocus', models.BooleanField()),
                ('autocomplete', models.BooleanField()),
                ('required', models.BooleanField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.field')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TAB_FORM', 'TAB_FORM'), ('COLLECTION_FORM', 'COLLECTION_FORM'), ('LINEAR_FORM', 'LINEAR_FORM')], max_length=200)),
                ('sub_type', models.CharField(choices=[('LINEAR_COLLECTION', 'LINEAR_COLLECTION'), ('HORIZONTAL_COLLECTION', 'HORIZONTAL_COLLECTION'), ('CUSTOM_COLLECTION', 'CUSTOM_COLLECTION'), ('PAGE_COLLECTION', 'PAGE_COLLECTION'), ('HORIZONTAL_TAB', 'HORIZONTAL_TAB'), ('VERTICLE_TAB', 'VERTICLE_TAB')], max_length=200)),
                ('form_name', models.CharField(default=' ', max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.CreateModel(
            name='FormAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=2048)),
                ('target', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=4)),
                ('autocomplete', models.CharField(max_length=10)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('serial_number', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Section', to='forms.section'),
        ),
        migrations.CreateModel(
            name='FieldStyling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.border')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.field')),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.layoutsizing')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.text')),
                ('visuals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.visuals')),
            ],
        ),
    ]
