# Generated by Django 5.1 on 2024-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
